<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <div class="container">
        <form action="/login/index" method="POST">
            <h2>Login</h2>
            <label for="email">Email: </label>
            <input type="text" name="email" placeholder="email">
            <br>
            <label for="password">Password: </label>
            <input type="text" name="password" placeholder="password">
            <br>
            <input type="submit" name="login" value="Login">
        </form>
    </div>
</body>

</html>