<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<style>
    input {
        width: 80%;
    }
</style>

<body>
    <form action="/index/addproduct" method="POST">
        <div class="row">

            <div class="col">
                <h3 id="fieldheading"></h3>
                <div id="newRow"></div>
            </div>

            <div class="col text-center">
                <h2 class="text-center">Add Product</h2><br>
                <label for="product_name">Product Name: </label>
                <input type="text" name="product_name"><br>
                <label for="product_category">Product Category: </label>
                <input type="text" name="product_category"><br>
                <label for="product_price">Product price: </label>
                <input type="text" name="product_price"><br>
                <label for="product_stock">Product stock: </label>
                <input type="text" name="product_stock"><br>
                <div class="row mt-2">
                    <div class="col">
                        <button id="addRow" type="button" class="btn btn-info">Add More Fields</button>
                    </div>
                    <div class="col">
                        <button id="addVariation" type="button" class="btn btn-info">Add Variations</button>
                    </div>
                </div>
                <input type="submit" name="addproduct" value="Add Product" class="btn btn-success col-6 mt-2">

                <div class="mt-1">
                    <?php
                    if (isset($productaddmsg)) {
                        echo $productaddmsg;
                    }
                    ?>
                </div>
            </div>

            <div class="col">
                <h3 id="variationheading"></h3>
                <div id="newVariation"></div>
            </div>
    </form>
    </div>
    <div class="text-center">
        <a href="/index/product" class="btn btn-danger">Show Products</a>
    </div>
</body>
<script type="text/javascript">
    // add row
    $("#addRow").click(function() {
        document.getElementById('fieldheading').innerHTML = "Add Fields";
        var html = '';
        html += '<div id="inputFormRow" class="row">';
        html += '<div class="input-group mb-3">';
        html += '<input type="text" name="field[]" class="form-control m-input" placeholder="Enter title" autocomplete="off"><input type="text" name="value[]" class="form-control m-input" placeholder="Enter title" autocomplete="off">';

        html += '<div class="input-group-append">';
        html += '<button id="removeRow" type="button" class="btn btn-danger">Remove</button>';
        html += '</div>';
        html += '</div>';

        $('#newRow').append(html);
    });

    // remove row
    $(document).on('click', '#removeRow', function() {
        $(this).closest('#inputFormRow').remove();
    });
</script>

<script type="text/javascript">
    // add row
    $("#addVariation").click(function() {
        document.getElementById('variationheading').innerHTML = "Add Varitions";
        var html = '';
        html += '<div id="inputFormRow" class="row">';
        html += '<div class="input-group mb-3">';
        html += '<input type="text" name="variation1[]" class="form-control m-input" placeholder="Enter title" autocomplete="off"><input type="text" name="variation2[]" class="form-control m-input" placeholder="Enter title" autocomplete="off"><input type="text" name="variation3[]" class="form-control m-input" placeholder="Enter title" autocomplete="off">';

        html += '<div class="input-group-append">';
        html += '<button id="removeRow" type="button" class="btn btn-danger">Remove</button>';
        html += '</div>';
        html += '</div>';

        $('#newVariation').append(html);
    });

    // remove row
    $(document).on('click', '#removeRow', function() {
        $(this).closest('#inputFormRow').remove();
    });
</script>

</html>