<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.88.1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <title>Dashboard Template · Bootstrap v5.1</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.1/examples/dashboard/">



    <!-- Bootstrap core CSS -->
    <link href="../node_modules/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" crossorigin="anonymous">


    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            user-select: none;
        }

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }
    </style>


    <!-- Custom styles for this template -->
    <link href="./assets/css/dashboard.css" rel="stylesheet">
</head>

<body>

    <header class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
        <a class="navbar-brand col-md-3 col-lg-2 me-0 px-3" href="#">Company name</a>
        <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-nav">
        </div>
    </header>
    <div class="container-fluid">
        <div class="row">
            <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
                <div class="position-sticky pt-3">
                    <ul class="nav flex-column">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="/index/product">
                                <span data-feather="home"></span>
                                Products
                            </a>
                        </li>

                    </ul>
                </div>
            </nav>

            <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
                <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
                    <h1 class="h2">Edit Product</h1>
                </div>
                <form class="row g-3" method="POST" action="/index/updateproduct">
                    <div class="col-md-7">
                        <label for="product_name" class="form-label">Product Name</label>
                        <input type="text" class="form-control" id="product_name" name="product_name" value="<?php echo $data->product_name; ?>">
                    </div>
                    <div class="col-md-7">
                        <label for="product_category" class="form-label">Product Category</label>
                        <input type="text" class="form-control" id="product_category" name="product_category" value="<?php echo $data->product_category; ?>">
                    </div>
                    <div class="col-md-7">
                        <label for="product_price" class="form-label">Product Price</label>
                        <input type="text" class="form-control" id="product_price" name="product_price" value="<?php echo $data->product_price; ?>">
                    </div>
                    <div class="col-md-7">
                        <label for="product_stock" class="form-label">Product Stock</label>
                        <input type="text" class="form-control" id="product_stock" name="product_stock" value="<?php echo $data->product_stock; ?>">
                    </div>
                    <input type="hidden" name="id" value="<?php echo $data->_id; ?>">

                    <?php
                    // error_reporting(0);
                    $length = count($data->additional);
                    $html = "<h3>Addtional Fields</h3>";
                    if (!$length == 0) {
                        foreach ($data->additional as $k => $v) {
                            $html .= '<div id="inputFormRow" class="row">
                            <div class="input-group mb-3">
                            <input type="text" name="field[]" value=' . $k . ' class="form-control m-input">
                            <input type="text" name="value[]" value=' . $v . ' class="form-control m-input">
                        </div></div>';
                        }
                        echo $html;
                    }
                    ?>

                    <!-- <?php
                            $html1 = "<h3>Variations</h3>";
                            foreach ($data->varitions as $k => $v) {
                                foreach ($v as $b) {
                                    echo $b;
                                    print_r($v[0]);
                                    echo $k;
                                    $html1 .= '<div id="inputFormRow" class="row">
                                <div class="input-group mb-3">
                                <input type="text" name="field" value=' . $b . ' class="form-control m-input" placeholder="Enter title" autocomplete="off">
                                <input type="text" name="value" value=' . $b . ' class="form-control m-input" placeholder="Enter title" autocomplete="off">
                                <input type="text" name="field" value=' . $b . ' class="form-control m-input" placeholder="Enter title" autocomplete="off">
                                </div></div>';
                                }
                                echo $html1;
                            }
                            ?> -->
                    <div class="col-12">
                        <button type="submit" class="btn btn-primary" name="update" value="blog">Update Product</button>
                    </div>
                </form>
            </main>
        </div>
    </div>


    <script src="../node_modules/bootstrap/dist/js/bootstrap.bundle.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

</body>

</html>