<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <div class="container">
        <h2>Signup</h2>
        <form action="/signup/register" method="POST">
            <label for="name">Name: </label>
            <input type="text" name="name">
            <br>
            <label for="email">Email: </label>
            <input type="text" name="email">
            <br>
            <label for="password">Password: </label>
            <input type="text" name="password">
            <br>
            <input type="submit" name="register" value="Register">
        </form>
</body>
</div>

</html>